language: go

go:
  - "1.7.4"
  - "1.7.6"
  - "1.8.7"
  - "1.9.5"
  - "1.10.1"
  - master

go_import_path: github.com/Neo23x0/simplesyslog
notifications:
  email: false
  slack: nextron-systems:51vB5h6MxkSbX5iMpscrvOza
